### PR TITLE
Added a command line argument that sets a sleep timer in minutes

### PR DESCRIPTION
**Pull request by cpenning**
minor feature addition -- added a sleep timer option to save my spouse's sanity.

### CODE REVIEW

**Comment by cpenning** [comment]
Regarding the travis-ci failure, it [looks](https://github.com/codecov/codecov-python/issues/46) like an issue with  the `coveragepy` package and not a real problem with my code.

**Comment by borgstrom** [comment]
Thanks for the contribution!  A couple things...

Now that we're going to be using signal for more than just debug let's move `import signal` up with the other imports.

Then we can separate the two blocks out so that their two different conditions (i.e. Don't do `if args.debug or args.timer:`, just add a new block under the `if args.debug` for your new `if args.timer`)

Make sense?

Once updated we'll see if Travis is still having issues and we'll get this merged.

**Comment by cpenning** [comment]
Thanks for a great project -- it is exactly what I needed.

I was debating which way to go with the signal import. I also considered doing a custom exception for the signal handler to allow for a fade-out of the sound, but figured I'd keep it simple for now.

travis-ci seems to still be unhappy at python 3.2. In the similar issue I linked above, stevepeak said:

> This error looks like it comes from the `coveragepy` package. Are you able to install this package in your environment?
> 
> Lets try: `pip install coverage==3.7.1 codecov` (I recall hearing issues with 3.2 and coverage v4)

And gappleto97 (the original reporter) responded:

> This definitely fixes things. I added a flag to my `.travis.yml` script to only install 3.7.1 on python 3.2.*. I've also made sure that all of my coverage checks are done with allowed failure. Thanks for the help.

I have not yet used travis-ci so I don't know if this is useful or not, but the stacktrace looks almost identical (except ours has `coverage==4.0.3` instead of `coverage==4.0.2`).

**Comment by borgstrom** [comment]
Python 3.2 is end of life, so I say we just drop it from the travis file.  Can you add the updated travis file to this PR and we'll get this merged.

**Comment by cpenning** [comment]
Nah, fixing it was trivial. Had nothing to do with the code, just my ignorance. Thanks from prompting me to slightly shrink that ignorance.

**Comment by borgstrom** [comment]
Merged.  Thanks for the contribution @cpenning!

**Pull request merged**
